version: "3.8"
services:
  backend1:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: node server.js 3001

  backend2:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: node server.js 3002

  backend_backup:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: node server.js 3003

#  nginx:
  haproxy:
#    image: nginx:latest
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - backend1
      - backend2
      - backend_backup